version: "2"
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    # 镜像名称
    image: codebub-library:1.0.0
    ports:
      - 5000:80
    restart: always
    # 容器名称
    container_name: "codebub-library"